page_title: | Great ideas should not be lost. 

meta_description: | Answer My Office is a Professional Live Answering Service. Friendly receptionists answer your calls. Sound corporate! Need your calls answered? Tailored to Your Business Call Now! Have your calls professionally answered. We offer a 7 DAY FREE TRIAL.

meta_keywords:
  - Answer Service


imap_server: imap.gmail.com
imap_port: 993
imap_username: elton.stewart@gmail.com
imap_password: xpan2007